### ISSUE TITLE
Attribute integrity in this code (adding booststrap)

### ISSUE THREAD

**Issue by fffeelipe** [goldironhack/2017-Purdue-UNAL-IronHack-Tutorials#2]
When I copy-paste the code in netbeans, a warning appears:
"attribute integrity is not allowed on element link at this point"
Why? how do I solve it?
Is it really necesary to have this attribute?

**Comment by RCODI** [comment]
Integrity is a new attribute defined in SRI for both script and link tags.

More detail: 
Integrity attribute is to allow the browser to check the file source to ensure that the code is never loaded if the source has been manipulated.
Crossorigin attribute is present when a request is loaded using 'CORS' which is now a requirement of SRI checking when not loaded from the 'same-origin'.

You can safely assume that the Netbeans  hasn't been updated to include SRI support just yet. Open your webpage with chrome you will found warning disappeared.

**Comment by RCODI** [comment]
Please let me know if you have any other question.

**Comment by fffeelipe** [comment]
Thanks, your response was very helpful. :) 
I don't have any other question by now.

**Comment by RCODI** [comment]
Thank you! Have a good day!
